site_name: " BMS Documentation "
site_url: https://in.linkedin.com/company/bookmyshow
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide #When autohiding is enabled, the header is automatically hidden when the user scrolls past a certain threshold, leaving more space for content.
  language: en
  palette: 
    scheme: bms
extra_css:  
  - stylesheets/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BMSDocs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bookmyshow
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/company/bookmyshow
plugins:
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
    - User Documentation : 
      - User Documentation/User Documentation.md
      - User Documentation/User Guides.md
      - User Documentation/Quick Reference Guides.md
      - User Documentation/FAQ's.md
      - User Documentation/Video Tutorials.md
    - Developer Documentation:
      - Developer Documentation/index.md
      - Developer Documentation/Tech Stacks.md
      - Developer Documentation/Databases.md
      - Developer Documentation/SDK Docs.md
    - Partner Documentation:
      - Partner Documentation/API Documentation.md
      - Partner Documentation/Architecture Diagrams.md 
      - Partner Documentation/Tech Stacks.md
      - Partner Documentation/Databases.md
      - Partner Documentation/SDK Docs.md
    - Blogs:
      - Blogs/Blogs.md
    - Newsletter:
      - Newsletter/Newsletter.md
    - What's New:
      - What's New/SPICE.md
      - What's New/New Tech Features.md
copyright: |
  &copy; 2023 <a href="https://github.com/BMSDocs"  target="_blank" rel="noopener">BMS Documentation</a>

